const actionTypes = {
    SET_CATEGOTY: "SET_CATEGORY",
    ADD_TO_CART: "ADD_TO_CART",
    SET_CART_EMPTY: 'SET_CART_EMPTY',
    DELETE_FROM_CART: "DELETE_FROM_CART",
    SET_QUANTITY: "SET_QUANTITY",
    SET_DETAILS_PRODUCT: 'SET_DETAILS_PRODUCT',
    OPEN_TOAST: "OPEN_TOAST",
    CLOSE_TOAST: "CLOSE_TOAST"
}
export default actionTypes